import pathlib
import soundfile as sf

from kokoro_onnx import Kokoro

dependency_path = pathlib.WindowsPath(__file__).parent / "dependencies"

kokoro = Kokoro(dependency_path / "kokoro-v1.0.onnx", dependency_path / "voices-v1.0.bin")
samples, sample_rate = kokoro.create(
    "Hello. This audio generated by kokoro!", voice="af_sarah", speed=1.0, lang="en-us"
)
sf.write("audio.wav", samples, sample_rate)
print("Created audio.wav")